services:
  crawler:
    # 使用我们之前构建的自定义镜像
    image: crawl4ai-xcom
    # 不会自动重启，任务完成后即退出
    restart: "no"
    # 确保容器能通过 host.docker.internal 找到宿主机
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 挂载外部配置文件和认证文件
    volumes:
      - "/home/gyq/workspace/game_data/resources/xcom_auth/.env:/app/.env"
      - "/home/gyq/workspace/game_data/resources/xcom_auth/auth_state.json:/app/auth_state.json"
    # 设置环境变量
    environment:
      - PROXY_SERVER=http://host.docker.internal:7890
      - AUTH_JSON_PATH=/app/auth_state.json
    # 要在容器内执行的完整命令
    command: >
      python -m crawl4ai.crawlers.x_com.production_crawler
      --keyword "generative AI"
      --scan-scrolls 3
      --max-replies 10
      --reply-scrolls 8
      --output-method kafka
      --kafka-key-prefix "x.com"
